import manifest from '@/assets/images/manifest.json';

/**
 * Image resolution against the build-time manifest.
 *
 * Components ask for an image by the same public path that lives in
 * `site.json`; the manifest (generated by `npm run images`) supplies the
 * responsive srcset, intrinsic dimensions and a base64 blur-up placeholder.
 * When an image is missing from the manifest we fail soft so the layout never
 * shows a broken asset.
 */
export interface ResolvedImage {
  src: string;
  fallbackSrc: string;
  srcset: string;
  srcsetFallback: string;
  width: number;
  height: number;
  lqip: string;
  /** intrinsic aspect ratio, used to reserve layout space (prevents CLS). */
  aspectRatio: number;
}

const table = manifest as Record<
  string,
  Omit<ResolvedImage, 'aspectRatio'> & { aspectRatio?: number }
>;

export function resolveImage(publicPath: string): ResolvedImage | null {
  const entry = table[publicPath];
  if (!entry) return null;

  const aspectRatio = entry.width > 0 ? entry.width / entry.height : 1;
  return { ...entry, aspectRatio };
}

/** Small helper: a stable `sizes` hint by breakpoint class. */
export function sizesFor(kind: 'full' | 'half' | 'third' | 'card'): string {
  switch (kind) {
    case 'full':
      return '100vw';
    case 'half':
      return '(max-width: 768px) 100vw, 50vw';
    case 'third':
      return '(max-width: 768px) 100vw, 33vw';
    case 'card':
      return '(max-width: 640px) 92vw, (max-width: 1024px) 60vw, 40vw';
    default:
      return '100vw';
  }
}
